### ISSUE TITLE
CBUS PIR sensors as binary / lux entities?

### ISSUE THREAD

**Issue by arrikhan** [autoSteve/acMqtt#13]
Hi, 

Is it possible to expose cbus pir sensors ? I believe occupancy (motion) and lux levels may be available?

**Comment by autoSteve** [comment]
Set up a group to trigger on movement with a short timer like 5s in the block and:
MQTT, bsensor, sa=Carport, on=Motion detected, off=No motion

LUX is not available AFAIK. For some sensors, like the 5753PEIRL the light level may be broadcast periodically as a 0-255 group.
MQTT, sensor, sa=Carport, pn=Carport Light Level, unit=%, dec=0, scale=0.390625,

**Comment by arrikhan** [comment]
Brilliant! Thanks so much for this solution. I have eight of these sensors and they've now become useful for HA automation outside of CBUS. Is it worth adding this to the readme (ie: how to combine your bsensor configuration for CBUS PIR sensors?). Us lesser beings sometimes haven't put 2 and 2 together in setting up 'virtual' CBUS groups to link to the sensors to complete the puzzle.

**Comment by autoSteve** [comment]
😅 Hardly a lesser being mate. Just consider yourself smarter. We're smarter every day.

Glad to hear it. I've done this so many times with PIR sensors that it ceases to be a 'trick', just "what do"...

Cheers, and glad it helped.

**Comment by manningoz** [comment]
Is it possible to add a single group (say a sensor) as two instances of different types of devices. For example if there is a motion sensor, to have it as a sensor ie MQTT, sensor, sa=Carport, on=Motion detected, off=No motion AND another as a switch MQTT, switch, sa=Carport so you can manually override the detection?
