### ISSUE TITLE
[Feature Request] Airtopia AC Control

### ISSUE THREAD

**Issue by ziogref** [autoSteve/acMqtt#16]
Hi Steve,

Would like to request a feature. I have 2 Daikin AC units that are connected using Airtopia units (I think the company is basically dead now).

My 2 Airtopia units are added to CBUS via Modbus and are in group 250 (I think this is the correct terminology)

In my CBUS webUI, under objects I have the following entries
local/User Parameter/Lounge AC Power
local/User Parameter/Lounge AC Set Point
local/User Parameter/Lounge AC Mode
local/User Parameter/Lounge AC Fan
local/User Parameter/Lounge AC Vertical Swing
local/User Parameter/Lounge AC Protocol ID
local/User Parameter/Lounge AC Temperature Sensor
local/User Parameter/Lounge AC Current Sensor
local/User Parameter/Lounge AC Dry Contact

Is it possible to add these devices to Home assistant? I added the Tag 'AC' to one of the units but in MQTT explorer it showed up outside of the home assistant topic so I couldn't add it. 

attached is a screenshot on how they appear in CBUS

I greatly appreciate your work on this, getting my lights added to HA has been a game changer.

![Screenshot from 2023-08-07 16-17-15](https://github.com/autoSteve/acMqtt/assets/16585623/5baee485-273c-44c0-99fe-cce20f2d1885)

**Comment by autoSteve** [comment]
A fascinating prospect.

There is a HomeAssistant module called "MQTT HVAC", whose configuration should be able to be shoehorned into a 'homeassistant' MQTT discovery topic ex. SHAC to avoid much YAML. Then code could be written on the SHAC to read/write appropriate state/action topics and sync those user parameters to the MQTT broker. I think... It may be reasonably straightforward. Or would be if I had one of those Airtopia suckers to play with.

So if you change the values of the user parameters in CBus does that cause action at the Air Conditioner? i.e. if you set 0/250/3 "Lounge AC Power" to the value of "power on (1)" (presumably) does magic happen at the AC?

Tagging stuff as "AC" with my code is for ESPHome interaction, where I replace the stupid Panasonic "cloud" based WiFi embedded controllers with ESP32 SOCs running code written by other much smart folks, which talk directly to HA. Mostly because Panasonic's cloud service is dodgy and super slow. The AC tagging on my NAC lets me control the devices from both HA and also NAC visualisations/timers. I'm screen bisexual here, with an iPad for NAC viz and also HomeAssistant on PC browser (which mostly is my interface to Google Home). "Hoy Gooogz, turn on the air con, luv, would ya?", or stroll to the iPad if I'm feeling like a work-out and press a button... Or turn the shed AC on automatically to cool the servers on hot days, without Panasonic cloud being down and baking my servers in 40C heat...

**Comment by ziogref** [comment]
> So if you change the values of the user parameters in CBus does that cause action at the Air Conditioner? i.e. if you set 0/250/3 "Lounge AC Power" to the value of "power on (1)" (presumably) does magic happen at the AC?

So setting 0/250/3 "Lounge AC Power" to the value of "power on (1)", the CBUS system contacts the Airtopia black box via MODBUS who then sends signal up to the AC unit which has an IR blaster stuck onto the IR receiver of the Daiken.
It's basically a glorified IR blaster. The airtopia unit is completely ignorant to the state of the AC if it changes via the remote, the Airtopia just keeps track of what it last sent as the last known state/setting.

So maybe this will help? Here are the "Levels" in the cbus objects. Each image file name is the Cbus address and name.
![0-250-3-power](https://github.com/autoSteve/acMqtt/assets/16585623/d5b6ecaf-6ca2-4caf-a5d9-2374419ad48b)
![0-250-5-mode](https://github.com/autoSteve/acMqtt/assets/16585623/09284764-c2d1-4703-9cfa-aa30fab212e1)
![0-250-7-VerticalSwing](https://github.com/autoSteve/acMqtt/assets/16585623/7572ba3b-aa7d-4445-b1b4-dac99d284cf6)
![0-250-8-HorizontalSwing](https://github.com/autoSteve/acMqtt/assets/16585623/b7fc8447-2e13-41e8-afc0-39a82bf7f33f)

The following items have a "Data Type" of 12. 4 byte unsigned integer
0/250/3 (Power)
0/250/4 (Set point, aka Set temperature) 
0/250/5 (Mode)
0/250/6 (Fan)
0/250/7 (Vertical Swing)
0/250/8 (Horizontal Swing)
0/250/9 (Protocol ID)

These are all useable controllable. All are self explanatory except Protocol ID, I believe this is the data base entry for the type of remote the airtopia unit emulates. Not really needed in HA

The following are Sensors and have a "Data Type" of 14. 4 byte floating point
0/250/10 (Temperature Sensor) 
0/250/11 (Current Sensor, I believe this is a CT clamp)

and lastly, 1 more sensor that has a "Data Type" of 12. 4 byte unsigned integer
0/250/12 (Dry Contact) 

Not sure what the last one is? maybe compressor state? Dunno. 

Is this info helpful?

**Comment by autoSteve** [comment]
Most helpful. Out of interest, what model is your Daikin A/C? Does it have an S21 port?

**Comment by ziogref** [comment]
> Most helpful. Out of interest, what model is your Daikin A/C? Does it have an S21 port?

I have a RXS25LVMA / FTX525LVMA
And
RXS71LVMA / FTXS71LVMA

No idea what an S21 port is.

**Comment by autoSteve** [comment]
The FTXS71LVMA seems to have an S21 protocol connector. And if you made a typo, then the FTX**S**25LVMA also does.

I have seen a fascinating project on Github relating to S21. https://github.com/joshbenner/esphome-daikin-s21. This uses an ESP32 device with ESPHome to plumb in Daikin A/Cs to HomeAssistant. Some soldering seems to be required... plus acquisition of quite cheap ESP32 WiFi devices. A very similar solution to what I do with my Panasonic A/Cs.

**Comment by ziogref** [comment]
Huh. I will have to disassemble my daikens cause I have NO IDEA how the airtopia units intergrate.

However the airtopia units to get the current of the device, that would be super handy to have for power monitoring in HA.

**Comment by ziogref** [comment]
Ok, so pulled apart the bedroom AC and it looks like it has an S21 port 
![PXL_20230809_071652632](https://github.com/autoSteve/acMqtt/assets/16585623/88c9dd1a-0111-49c0-aae2-d464d1707822)

And it is just a CT clamp getting the consumption information.

But because of all the extra CBUS/airtopia wiring in the Unit it was a complete cunt to put back together.

I think S21 would be excellent in the future (probably I would get the faiken esp32 for $60aud) as my airtopia doesn't support quiet mode, which would be amazing to have.

But I don't have $120+shipping at the moment. So maybe Christmas time.

Thanks for investigating the option to use Airtopia.
I had a look at the code and was immediately lost. Lua makes no sense to me (I dabble in BASH, Powershell and python)

**Comment by autoSteve** [comment]
LUA. I hear you. Python is my day job, and the number of times I stuff up not-equal  != / ~=  syntax when I've been doing LUA of an evening don't bear counting. 🤦🏻

**Comment by autoSteve** [comment]
Ugh. I just typed a giant message that went "*poof*" for some reason 🤦🏻. So a short version...

I've added limited experimental Airtopia support @ziogref.

Supports power, mode and target temperature only, no sensors. Check out the comments at top of script, and ping if you get stuck. Should only need sa= (suggested area) for only one user param (but MUST be included for at least one.)

I want to know whether basic set temp/mode/off work as expected with a Daikin. Then I'll take it further with sensors/etc.

Here are my basic examples...
Power user param ... AT, dev=test, sa=Bathroom 1, func=power, 
Temp user param ... AT, dev=test, func=target_temperature, 
Mode user param ... AT, dev=test, func=mode,

**Comment by ziogref** [comment]
@autoSteve 
Works like a charm, except multi-device appears to not be working.

If I add the bedroom, it does not appear in HA, however it will start taking all the commands for the living room.

If I have just the living room configured in CBUS, that unit receives all the commands. Power on works as soon as a mode is selected (and off), the unit receives all the modes and the temp changes also work.

**Comment by autoSteve** [comment]
Good to hear. For multiple devices, maybe they are ending up with the same 'dev' name? If they were both called 'Daiken' or 'A/C' that would cause a collission. I can avoid that with some code...

**Comment by ziogref** [comment]
> Good to hear. For multiple devices, maybe they are ending up with the same 'dev' name? If they were both called 'Daiken' or 'A/C' that would cause a collission. I can avoid that with some code...

Of course.

My dumbass read dev=test
As devolopment=test
Not device.

**Comment by autoSteve** [comment]
Right. Some further experimental code in a commit...

1) You will most certainly need MQTT Explorer based on your current broker topics. Go and kill the existing airtopia/cbus_mqtt_{dev} topics with delete. And the homeassistant/climate topics. Otherwise you will get duplicates in the HomeAssistant lovelace UI... The reason is that I have changed airtopia naming to {suggested area}_{device}. This means you can name each dev= as something like 'Daikin', and as long as the rooms are different this will work. i.e. Lounge, Daikin and Bedroom 1, Daikin. If you're stuck on this, reach out.

2) I have added support for current_temperature ... but how to do current consumption well is currently a head-f, so still to-do.

3) I have added support for swing modes. vert_swing and horiz_swing. Tag the SHAC objects, and once done select the swing mode in the lovelace settings for the Airtopia object.

4) Most changes on CBus are not properly reflected in HomeAssistant yet... TODO. So this is mostly a HA->CBus thing at the moment, and most change in CBus will not be picked up by HA.

Feedback requested.

**Comment by autoSteve** [comment]
I have also noticed that some MQTT topics do not appear 'persistent' for me, notably the discovery topics. So on a re-start of HomeAssistant the climate entries will show as 'unavailable'. I currently have no idea why this is, as the code sets a PERSIST flag for these topics, but seems to be ignored. Ugh. Restart the MQTT send / receive script to get them back after a HA restart. I'd be interested to learn if this is not an issue for you ... i.e. restart HA, do the Daikin's show as available or does it require a script restart to get to them again?

**Comment by ziogref** [comment]
Funny thing. I already had MQTT explorer open (ESPresense setup) 
Updated the script, rebooted all scripts and its cooked. MQTT explorer is showing CBUS as offline. Made sure the MQTT details were correct in the lua config. 

Reverted back the code you pushed to github 2 days ago and CBUS is back online again

**Comment by autoSteve** [comment]
How odd. Were there any SHAC error logs thrown? Works fine for me.

**Comment by ziogref** [comment]
> How odd. Were there any SHAC error logs thrown? Works fine for me.


Resident script:909: attempt to concatenate global 'dev' (a nil value)
stack traceback:
 Resident script:909: in function 'func'
 
 Stacks of these

(learning more about cbus every day atm)

**Comment by autoSteve** [comment]
My bad. New commit. Oops.

**Comment by ziogref** [comment]
Ok, so swinging is working. 

I have power, mode, swing and desired temp

current temp cant see how to tag that. I can see that you have it in the code but cant see what to tag it as.

Also a note on the power consumption, its in amps, not watts. I can do the conversion in HA if it can be passed through as a sensor (My solar reports the current voltage. so volts x amps = watts)

**Comment by autoSteve** [comment]
For current temp, try something like "AT, dev=mydaiken, sense=current_temperature, "...

The MQTT HVAC has discovery for the current temperature built in. It displays it as a big number in the middle of the dial. For current I need to work out a sensible name for the discovered sensor. Getting it in to MQTT is relatively easy, just need to cope with tagging adds/moves/changes. How about "mydaiken Power Consumption"? so "{device name} Power Consumption", which would get a discovery topic under homeassistant/sensor/{uid}/. The unit_of_measure would be "A". Tagging like "AC, dev=mydaiken, sense=power_consumption, ".

I should be able to have a go at that tonight.

**Comment by ziogref** [comment]
> For current temp, try something like "AT, dev=mydaiken, sense=current_temperature, "...
> 
> The MQTT HVAC has discovery for the current temperature built in. It displays it as a big number in the middle of the dial.

this works!

For current I need to work out a sensible name for the discovered sensor. Getting it in to MQTT is relatively easy, just need to cope with tagging adds/moves/changes. How about "mydaiken Power Consumption"? so "{device name} Power Consumption", which would get a discovery topic under homeassistant/sensor/{uid}/. The unit_of_measure would be "A". Tagging like "AC, dev=mydaiken, sense=power_consumption, ".
> 
> I should be able to have a go at that tonight.

Yeah sounds good, I have done a bit of research to gets actual useful data from that sensor it needs to update as frequently as possible. I will be able to grab the volts of my house from my solar inverter which I can get a read out in KW how much each AC is using. I can then throw that into a HA meter and get kWh readings. I understand the timing from CBUS --> MQTT --> HA is not instant and can get seconds, but as frequent as you can would be amazing.

**Comment by autoSteve** [comment]
> CBUS --> MQTT --> HA is not instant and can get seconds, but as frequent as you can would be amazing.
The script should update the broker in near real time. The "AT" script will fire as soon as any change in value is detected on the SHAC, and this sends a socket message to "MQTT Send Receive", which (unless its busy doing something else) will publish to the broker. HA is subscribed to the sensor topic, so should also update without delay. MQTT is pretty quick.

I have no idea how often the Airtopia sends to modbus, but that might be the appreciable delay.

**Comment by ziogref** [comment]
> > CBUS --> MQTT --> HA is not instant and can get seconds, but as frequent as you can would be amazing.
> 
> The script should update the broker in near real time. The "AT" script will fire as soon as any change in value is detected on the SHAC, and this sends a socket message to "MQTT Send Receive", which (unless its busy doing something else) will publish to the broker. HA is subscribed to the sensor topic, so should also update without delay. MQTT is pretty quick.
> 
> I have no idea how often the Airtopia sends to modbus, but that might be the appreciable delay.

Just tested turning on the AC from HA (from work, so over 5g on my phone) and checking my cbus on my work laptop and its was instant. So I guess we can assume instant. Will be very interesting ff the value changes much, but even if it does spam the broker, the MQTT broker it can handle it. That things is being smashed with 100's of updates every second from ESPresense.

**Comment by autoSteve** [comment]
Give "sense=power_consumption" a go, @ziogref. It'll create a discovery topic for a sensor called "{device name} Power Consumption". Well, it should.

**Comment by ziogref** [comment]
> Give "sense=power_consumption" a go, @ziogref. It'll create a discovery topic for a sensor called "{device name} Power Consumption". Well, it should.

well it works, maybe a little too well

this is the value in in HA
0.0399999991059303 A

Would it be hard to round it to say 4-5 decimal places?

**Comment by ziogref** [comment]
> I have also noticed that some MQTT topics do not appear 'persistent' for me, notably the discovery topics. So on a re-start of HomeAssistant the climate entries will show as 'unavailable'. I currently have no idea why this is, as the code sets a PERSIST flag for these topics, but seems to be ignored. Ugh. Restart the MQTT send / receive script to get them back after a HA restart. I'd be interested to learn if this is not an issue for you ... i.e. restart HA, do the Daikin's show as available or does it require a script restart to get to them again?

yes I have the same issue, had to restart the script

**Comment by autoSteve** [comment]
Sooo...

Add dec=4 as a keyword to the power sensor and you'll get four decimal places. And scale=1000 to get milliamps. Might need a script restart to get the initial rounding for existing sensor value.

> yes I have the same issue, had to restart the script

Glad it's not just me. But not glad that I have no idea why discovery is not persisting. I ask the broker to do it...

**Comment by ziogref** [comment]
@autoSteve don't worry about the scale, turns out the power use is only for the inside unit. (which makes sense) I got it all working in HA.But the inside unit will only ever pull a few hundred watts. 

The only thing missing from this now is fan speed.

**Comment by autoSteve** [comment]
Yeah, nah. The pedant in me has resurrected scale and units. Commit. 😅

**Comment by autoSteve** [comment]
You didn't give any details for what the acceptable fan speed values are. Happy to add, but I don't have any detail to go on.

**Comment by ziogref** [comment]
> You didn't give any details for what the acceptable fan speed values are. Happy to add, but I don't have any detail to go on.
> 
> (edit) Sez Interweb...
> 
> ```
> fan_modes:
>   - "1"
>   - "2"
>   - "3"
>   - "4"
>   - "auto"
> ```
> 
> But does "auto" = 5 or zero? Who can tell...

So it's just unassigned integer 32bit (same as set point)

You are correct it's 1-4 and auto. Trying to work out what auto is

**Comment by autoSteve** [comment]
Should I "bin" the potantial fan control? (Or rage at the sky a while longer?) Other values would indicate 1=auto, 2=1, 3=2, 4=3, 5=4.

Do let me know what you find out.

**Comment by ziogref** [comment]
Maybe just mark it as un-tested. I had a look at the documentation and its appears my setup is actually correct. I suspect something else is not right. I will need to talk to my integrator but I suspect he won't be able to help since AIrtopia seems to be dead.

**Comment by autoSteve** [comment]
The timing of when I publish the Airtopia discovery topics seems to be at play with the 'retain' flag not being set on publish to the broker, resulting in HA showing the devices as 'Unknown' status after restart. Weird. The latest commit fixes it in a brutally simple way. Note that the variable checkForChanges must be set to true.

I could have solved it in another way, avoiding checkForChanges, but that would have required a lot more code. That's on the "to do" list (and mught just stay there 😆)...

**Comment by ziogref** [comment]
Will try the new code but 2 nights now my CBUS system has freaked out. seems like after midnight something breaks and I need to delete all the topics out of the MQTT broker to fix it. Lights, fans, Airtopia etc all broke

This is in the CBUS error logs

```
Resident script:1414: bad argument #2 to 'format' (number expected, got nil)
stack traceback:
 [C]: in function 'format'
 Resident script:1414: in function 'outstandingMqttMessage'
 ```

I will add the new code you uploaded 20 hours ago and see if the issue pops up again

**Comment by autoSteve** [comment]
This section of code is now commented out. I think that's where the error is occurring...

```
    elseif parts[1] == 'airtopia' and parts[3] == 'state' then
      --[[
      device = parts[2]..'-'..parts[4]
      local net, app, group
      
      if atDevices[device] then
        alias = atDevices[device]
        local p = string.split(alias, '/'); net = tonumber(p[1]); app = tonumber(p[2]); group = tonumber(p[3])

        if ignoreCbus[alias] and os.time() - ignoreCbus[alias] > ignoreTimeout then -- Don't worry about older 'ignore' flags
          ignoreCbus[alias] = nil
          if logging then logger('Ignoring older CBus ignore flag for '..alias) end
        end
        if not ignoreCbus[alias] then -- Only set the CBus status/level if this script did not initiate the change, and if it is different to the current value
          local set = false
          local extant = GetUserParam(net, group)
          local e = tonumber(extant)
          if e ~= nil then
            if string.format('%.3f', e) ~= string.format('%.3f', tonumber(payload)) then SetUserParam(net, group, payload); set = true end
          else
            if extant ~= payload then SetUserParam(net, group, payload); set = true end
          end
          -- Setting CBus here will result in the AT event script requesting publication of the state using 1() above.
          -- This is undesired, so ignoreMqtt[alias] is used to ensure that the CBus change received does not publish to MQTT.
          --if set then ignoreMqtt[alias] = os.time() if logging then logger('Setting ignoreMqtt for '..alias..', oldState='..extant..' payload='..payload) end end
        else
          ignoreCbus[alias] = nil
          if logging then logger('Ignoring CBus publish for '..alias) end
        end
        at[alias].state = payload
      end
      --]]
    end
```

**Comment by autoSteve** [comment]
Hey @ziogref. My assumption is that atfans = {'Auto', '1', '2', '3', '4'} equals set the fan user parameter to {0, 1, 2, 3, 4}. Seems consistent with the rest of the Airtopia.

Keywords I used for the user param: "AT, dev=test, func=fan, "
With dev being the name of my non-existant testing device.

Happy testing.

How'd you get on with the system freak out post-midnight? All good now?

**Comment by ziogref** [comment]
So Airtopia hasn't been working for a while. Cant figure it.

I updated all the code to the latest version. Stop the scripts, launched MQTT explorer and deleted everything, started the cbus scripts and It all imported into HA. Changing the settings in HA show up in MQTT. Changing in CBus shows in MQTT but it appears Cbus is not reading the updates settings from MQTT.

After a bit of research this might make things easier for you. In CBUS, under MODBUS you can "add device" use the profile airtopia and mimic these settings
![image](https://github.com/autoSteve/acMqtt/assets/16585623/ef3eee71-8416-4954-a1ca-29ec6a81e0ee)

You should be able to see everything and you should be able to change values (power, mode, temp etc). It appears it doesnt really care that the device doesnt physically exist.

**Comment by autoSteve** [comment]
Take 2. When setting 'off' the mode should not be set in CBus... Yup, Half wit at times.

**Comment by ziogref** [comment]
Thanks mate, looks good.

**Comment by autoSteve** [comment]
Excellent. Re-open if there's further issue, @ziogref. I think this feature has run its course in the absence of fan speed testing, so have updated the readme and called it "supported".

**Comment by autoSteve** [comment]
I couldn't let it go... checkForChanges is no longer required for Airtopia, @ziogref. The latest commit should queue Airtopia devices for publishing discovery topics with a broker immediately upon script restart. Checking for changes should ensue...

**Comment by autoSteve** [comment]
Actually, hold off @ziogref. I think I've broken it...

**Comment by autoSteve** [comment]
I did broke it, but looks okay after latest commit. Some optimisation required for init for tomorrow or so, but it appears working, @ziogref.
