### ISSUE TITLE
Duplicate discovery topics in logs

### ISSUE THREAD

**Issue by lee-booy** [autoSteve/acMqtt#20]
Firstly thanks so much for these scripts they made my life so much easier. I set these up in a Spacelogic controller but in the Spacelogic logs I'm seeing 5500AC2 a duplicate removal, it just continues repeating forever for the same objects. 

HW: LSS5500SHAC (i.MX6)
SW: 1.14.0

No idea if this is relevant but my devices are 0/56/x in the objects screen

![CleanShot 2024-01-06 at 11 17 02@2x](https://github.com/autoSteve/acMqtt/assets/126991066/5cc6d754-aba8-48e0-ae4c-38c4ce255cc6)

![CleanShot 2024-01-06 at 11 12 02@2x](https://github.com/autoSteve/acMqtt/assets/126991066/a78a3575-58aa-4055-87eb-2295baf74161)
24 22:08:05

* string: Warning: Removing 4 duplicate discovery topics
MQTT send receive 06.01.2024 22:08:05
* string: Removed discovery topic homeassistant/light/cbus_mqtt_254_56_12/config
MQTT send receive 06.01.2024 22:08:05
* string: Removed discovery topic homeassistant/light/cbus_mqtt_254_56_45/config
MQTT send receive 06.01.2024 22:08:05
* string: Removed discovery topic homeassistant/light/cbus_mqtt_254_56_47/config
MQTT send receive 06.01.20
* string: Removed discovery topic homeassistant/switch/cbus_mqtt_254_56_27/config
MQTT send receive 06.01.2024 22:08:05
* string: Warning: Removing 1 duplicate discovery topics
MQTT send receive 06.01.2024 22:08:05
* string: Removed discovery topic homeassistant/switch/cbus_mqtt_254_56_28/config
MQTT send receive 06.01.2024 22:08:05
* string: Warning: Removing 3 duplicate discovery topics
MQTT send receive 06.01.2024 22:08:05
* string: Removed discovery topic homeassistant/light/cbus_mqtt_254_56_7/config
MQTT send receive 06.01.2024 22:08:05
* string: Removed discovery topic homeassistant/light/cbus_mqtt_254_56_13/config
MQTT send receive 06.01.2024 22:08:05
* string: Removed discovery topic homeassistant/light/cbus_mqtt_254_56_44/config
MQTT send receive 06.01.2024 22:08:05
* string: Warning: Removing 2 duplicate discovery topics
MQTT send receive 06.01.2024 22:08:05
* string: Removed discovery topic homeassistant/light/cbus_mqtt_254_56_12/config
MQTT send receive 06.01.2024 22:08:08
* string: Warning: Removing 3 duplicate discovery topics
MQTT send receive 06.01.2024 22:08:08
* string: Removed discovery topic homeassistant/switch/cbus_mqtt_254_56_27/config
MQTT send receive 06.01.2024 22:08:08
* string: Removed discovery topic homeassistant/light/cbus_mqtt_254_56_45/config
MQTT send receive 06.01.2024 22:08:08
* string: Removed discovery topic homeassistant/light/cbus_mqtt_254_56_47/config
MQTT send receive 06.01.2024 22:08:08
* string: Warning: Removing 1 duplicate discovery topics
MQTT send receive 06.01.2024 22:08:08
* string: Removed discovery topic homeassistant/switch/cbus_mqtt_254_56_28/config

**Comment by autoSteve** [comment]
How odd.

The code to detect and queue removal of duplicate MQTT discover topics under homeassistant/ is in the ON_MESSAGE callback. Try commenting out the detection code like the below and see if everything actually works.

I might need to add some logging in this function for you to more clearly show what's going on.

`client.ON_MESSAGE = function(mid, topic, payload)
  if contains('/cbus_mqtt_', topic) then
    -- Record discovery topics to check for duplication
    --local parts = string.split(topic, '/')
    --if parts[1] == string.split(mqttDiscoveryTopic, '/')[1] then
    --  if discovery[parts[3]] ~= nil then
    --    if discovery[parts[3]] ~= parts[2] then
    --      discoveryDelete[parts[3]..'/'..parts[2]] = true
    --    else
    --      discovery[parts[3]] = parts[2] -- Table of CBus addresses with type as the value
    --    end
    --  end
    --end
  else
    mqttMessages[#mqttMessages + 1] = { topic=topic, payload=payload } -- Queue the message
  end
end`

A full look at your keywords would be good. Something like:

<img width="1562" alt="image" src="https://github.com/autoSteve/acMqtt/assets/37229860/5202b701-cc84-4e3a-9944-3ddfc674b77f">

MQTT Explorer is a fantastic tool to see what's going on at the broker discover topics:

<img width="924" alt="image" src="https://github.com/autoSteve/acMqtt/assets/37229860/8146a2dd-0065-416e-9ed6-d713083e633b">

**Comment by autoSteve** [comment]
You could try this version of ON_MESSAGE to log what discovery dup detection might be doing.

```
client.ON_MESSAGE = function(mid, topic, payload)
  if contains('/cbus_mqtt_', topic) then
    -- Record discovery topics to check for duplication
    local parts = string.split(topic, '/')
    if parts[1] == string.split(mqttDiscoveryTopic, '/')[1] then
      if discovery[parts[3]] ~= nil then
        if discovery[parts[3]] ~= parts[2] then
          log(discovery)
          log(topic, mqttDiscoveryTopic, parts[3], discovery[parts[3]], parts[2])
          discoveryDelete[parts[3]..'/'..parts[2]] = true
        else
          discovery[parts[3]] = parts[2] -- Table of CBus addresses with type as the value
        end
      end
    end
  else
    mqttMessages[#mqttMessages + 1] = { topic=topic, payload=payload } -- Queue the message
  end
end
```

**Comment by autoSteve** [comment]
Righto. 0/56/27 is a light, and is tagged as such. The duplicate topic being deleted is a _switch_. The code is doing the right thing by killing off the switch, but why is a switch discovery topic being created for 0/56/27 in the first place?

Seeing your keywords in full for that one example might help, along with the logged dup delete.

<img width="433" alt="image" src="https://github.com/autoSteve/acMqtt/assets/37229860/bfdec6bb-d5af-4203-896d-4af269b79940">

**Comment by autoSteve** [comment]
I have replicated this I think, @lee-booy. I changed a light to a switch, and I am getting the log spammed. Re-starting the script sends everything back to normal.

There is an issue with dynamically changing from one type of discovery to another, and I am assuming this is what you did.

Looking into it.

**Comment by autoSteve** [comment]
Give the revised MQTT Send Receive script a test, @lee-booy. A simple fix.

Cheers.

**Comment by lee-booy** [comment]
Legend, pasted the updated script and logs are no longer spammed. Thanks so much 😄
