### ISSUE TITLE
Support for firmware 1.15.0+

### ISSUE THREAD

**Issue by sgraystar** [autoSteve/acMqtt#21]
Nice work with the scripts!!

Maybe related to the cleanup of issue #18 , when ramping from 255->0 the previous level in storage is not updated, preventing a subsequent ramp up from 0->255 being published.

Script version: current
Device: 5500AC2

Log extracts:
Light turned off/on without ramp, all OK.
```
MQTT 07.01.2024 15:40:23
* string: Setting 0/56/36 to 0.000, previous=255.000
MQTT Send Receive 07.01.2024 15:40:23
* string: Alias: 0/56/36, payload: 0, ramp rate: 0, target level: 0
MQTT Send Receive 07.01.2024 15:40:23
* string: Publishing state and level cbus/read/254/56/36 to OFF/0
MQTT 07.01.2024 15:40:32
* string: Setting 0/56/36 to 255.000, previous=0.000
MQTT Send Receive 07.01.2024 15:40:32
* string: Alias: 0/56/36, payload: 255, ramp rate: 0, target level: 255
MQTT Send Receive 07.01.2024 15:40:32
* string: Publishing state and level cbus/read/254/56/36 to ON/255
``` 

Light turned off/on with 4s ramp rate.
```
MQTT 07.01.2024 15:41:30
* string: Setting 0/56/36 to 0.000, previous=255.000
MQTT Send Receive 07.01.2024 15:41:30
* string: Alias: 0/56/36, payload: 0, ramp rate: 4, target level: 0
MQTT Send Receive 07.01.2024 15:41:30
* string: Set ramp for 0/56/36 and suppress zero send
MQTT Send Receive 07.01.2024 15:41:39
* string: Publishing state and level cbus/read/254/56/36 to OFF/0
MQTT Send Receive 07.01.2024 15:41:39
* string: Removing orphaned ramp for 0/56/36
MQTT 07.01.2024 15:41:41
* string: Not setting 0/56/36 to 255.000, previous value is 255.000
```

**Comment by autoSteve** [comment]
Humble thanks, @sgraystar.

An aside, looking at your log it seems less chatty than it should be. Over a four second ramp period there should be level updates received periodically. Is the event-based script 'MQTT' set to execute during ramping? (I ask because if you've updated firmware to 1.15.0 a bug was fixed regarding that feature. After 1.6.0 event scripts always executed during a ramp, which was unexpected behaviour.)

I can not replicate this yet. However I have observed some unexpected behaviour, with a ramp 0->255/4s not always triggering the "set ramp" logic, which is odd, and is distracting my attention. This results in periodic MQTT updates during a ramp, which is not desired, as #18 set out to avoid.

The previous stored value is set somewhere around line 1600, and this happens immediately after the final value gets published to MQTT (or it does for ramps now that I've slightly modified the code). This will happen when you see the log entry "Publishing state and level cbus/read/254/56/36 to OFF/0", which is logged by publish().

Given that, it's a bit of a head scratcher as to why the MQTT event script would call "Not setting". The 'pre' storage for that GA should have been set to zero!

I continue to look...

**Comment by autoSteve** [comment]
I've found it, @sgraystar.

(Plus found the annoying "why it no set ramp always?")

Notice the log entry "Removing orphaned ramp for 0/56/36". When this occurs, the 'pre' storage is not getting set because an alternate publish() call gets made outside of the ramp detection logic. I will commit an update that fixes this.

Ultimately, the best fix will be to rely on the bug fix in 1.15.0 for execute during ramping...

Most of the ramp detection code was made infinitely more complex because of this bug. Originally I had two 'MQTT' event scripts, with one executing during ramping, and the other not. Post 1.6.0 busted this, but the concept is now possible again. i.e. Send a message to MQTT send receive at the end of a ramp using a 'MQTT final' event script.

I am loathe to make this change at the moment, given 1.15.0 is so new, but might be able to code up something that falls back to the way the script works now for prior firmware, whilst also supporting getting end of ramp messages from an 'MQTT final' event script.

**Comment by sgraystar** [comment]
Glad I didn't completely waste your time. I am running sw 1.15.0 already, but did not have 'execute during ramping' set. Dunno why not.
Setting this was enough to rectify my issue.

**Comment by autoSteve** [comment]
You'll deffo want to use this latest commit for MQTT send receive, as it now updates storage on ramp orphan. And if you've never run 1.6.0 or earlier you would have had no idea about execute during ramping because it didn't matter what it was set to. 🤣 'Off' is the default for that check box.

**Comment by autoSteve** [comment]
Righto, @sgraystar. If you're up for it, I've added 1.15.0 optimisations.

Basically, the scripts check for 1.15.0, and the presense of a script called 'MQTT final'. If you choose to accept this, you'll need to add MQTT final (NOT execute during ramping), update MQTT and update MQTT send receive.

What this does is to look for 'final' levels of any lighting ramps, and deffo declares that as the final of a ramp. No bullshit ramp orphans. Or that's the plan.

It also checks on startup that MQTT is set to execute during ramp, and that MQTT final is set to NOT execute during ramp, mostly so other folks don't get smacked in the face with a rake handle like you after a 1.15.0 upgrade...

**Comment by sgraystar** [comment]
Updated just now, still seeing some problem with previous level.

Script version: commit 24868ae
Device: 5500AC2
Version: 1.15.0, hw v1.1

Reset / cleanup storage & reboot.
Light turned on/off/on without ramp.
```
MQTT 08.01.2024 08:22:28
* string: Setting 0/56/10 to 255.000, previous=not recorded
MQTT Send Receive 08.01.2024 08:22:28
* string: Alias: 0/56/10, payload: 255, ramp rate: 0, target level: 255
MQTT Send Receive 08.01.2024 08:22:28
* string: Publishing state and level cbus/read/254/56/10 to ON/255
MQTT 08.01.2024 08:22:28
* string: Set lastLevel to 255 for 0/56/10
MQTT 08.01.2024 08:22:28
* string: Saved last levels. Object(s) changed: 0/56/10 nil->255
MQTT 08.01.2024 08:22:38
* string: Setting 0/56/10 to 0.000, previous=255.000
MQTT Send Receive 08.01.2024 08:22:38
* string: Alias: 0/56/10, payload: 0, ramp rate: 0, target level: 0
MQTT Send Receive 08.01.2024 08:22:38
* string: Publishing state and level cbus/read/254/56/10 to OFF/0
MQTT 08.01.2024 08:22:47
* string: Setting 0/56/10 to 255.000, previous=0.000
MQTT Send Receive 08.01.2024 08:22:47
* string: Alias: 0/56/10, payload: 255, ramp rate: 0, target level: 255
MQTT Send Receive 08.01.2024 08:22:47
* string: Publishing state and level cbus/read/254/56/10 to ON/255
``` 

Light turned off/on with 4s ramp rate.
Note MQTT 08.01.2024 08:26:54, string: Not setting 0/56/10 to 0.000, previous value is 0.000
and MQTT 08.01.2024 08:27:36, string: Not setting 0/56/10 to 255.000, previous value is 255.000
```
MQTT 08.01.2024 08:26:51
* string: Setting 0/56/10 to 195.000, previous=255.000
MQTT Send Receive 08.01.2024 08:26:51
* string: Alias: 0/56/10, payload: 195, ramp rate: 4, target level: 0
MQTT Send Receive 08.01.2024 08:26:51
* string: Set ramp for 0/56/10
MQTT 08.01.2024 08:26:52
* string: Setting 0/56/10 to 135.000, previous=255.000
MQTT Send Receive 08.01.2024 08:26:52
* string: Alias: 0/56/10, payload: 135, ramp rate: 4, target level: 0
MQTT 08.01.2024 08:26:53
* string: Setting 0/56/10 to 75.000, previous=255.000
MQTT Send Receive 08.01.2024 08:26:53
* string: Alias: 0/56/10, payload: 75, ramp rate: 4, target level: 0
MQTT 08.01.2024 08:26:54
* string: Setting 0/56/10 to 15.000, previous=255.000
MQTT Send Receive 08.01.2024 08:26:54
* string: Alias: 0/56/10, payload: 15, ramp rate: 4, target level: 0
MQTT final 08.01.2024 08:26:54
* string: Sending final level for 0/56/10 of 0
MQTT Send Receive 08.01.2024 08:26:54
* string: Alias: 0/56/10, payload: 0, ramp rate: 4, target level: 0
MQTT Send Receive 08.01.2024 08:26:54
* string: Clear ramp for 0/56/10
MQTT Send Receive 08.01.2024 08:26:54
* string: Publishing state and level cbus/read/254/56/10 to OFF/0
MQTT 08.01.2024 08:26:54
* string: Not setting 0/56/10 to 0.000, previous value is 0.000
MQTT 08.01.2024 08:27:32
* string: Setting 0/56/10 to 37.000, previous=0.000
MQTT Send Receive 08.01.2024 08:27:32
* string: Alias: 0/56/10, payload: 37, ramp rate: 4, target level: 255
MQTT Send Receive 08.01.2024 08:27:32
* string: Set ramp for 0/56/10
MQTT 08.01.2024 08:27:33
* string: Setting 0/56/10 to 97.000, previous=0.000
MQTT Send Receive 08.01.2024 08:27:33
* string: Alias: 0/56/10, payload: 97, ramp rate: 4, target level: 255
MQTT 08.01.2024 08:27:34
* string: Setting 0/56/10 to 157.000, previous=0.000
MQTT Send Receive 08.01.2024 08:27:34
* string: Alias: 0/56/10, payload: 157, ramp rate: 4, target level: 255
MQTT 08.01.2024 08:27:35
* string: Setting 0/56/10 to 217.000, previous=0.000
MQTT Send Receive 08.01.2024 08:27:35
* string: Alias: 0/56/10, payload: 217, ramp rate: 4, target level: 255
MQTT final 08.01.2024 08:27:36
* string: Sending final level for 0/56/10 of 255
MQTT Send Receive 08.01.2024 08:27:36
* string: Alias: 0/56/10, payload: 255, ramp rate: 4, target level: 255
MQTT Send Receive 08.01.2024 08:27:36
* string: Clear ramp for 0/56/10
MQTT Send Receive 08.01.2024 08:27:36
* string: Publishing state and level cbus/read/254/56/10 to ON/255
MQTT 08.01.2024 08:27:36
* string: Not setting 0/56/10 to 255.000, previous value is 255.000
``` 

Turn of/on a few times without ramp to 'reset'.
Light turned off/on/off/on with 4s ramp rate.
Note, only one instance of Not Setting.
```
MQTT 08.01.2024 08:38:54
* string: Setting 0/56/10 to 243.000, previous=255.000
MQTT Send Receive 08.01.2024 08:38:54
* string: Alias: 0/56/10, payload: 243, ramp rate: 4, target level: 0
MQTT Send Receive 08.01.2024 08:38:54
* string: Set ramp for 0/56/10
MQTT 08.01.2024 08:38:55
* string: Setting 0/56/10 to 183.000, previous=255.000
MQTT Send Receive 08.01.2024 08:38:55
* string: Alias: 0/56/10, payload: 183, ramp rate: 4, target level: 0
MQTT 08.01.2024 08:38:56
* string: Setting 0/56/10 to 123.000, previous=255.000
MQTT Send Receive 08.01.2024 08:38:56
* string: Alias: 0/56/10, payload: 123, ramp rate: 4, target level: 0
MQTT 08.01.2024 08:38:57
* string: Setting 0/56/10 to 63.000, previous=255.000
MQTT Send Receive 08.01.2024 08:38:57
* string: Alias: 0/56/10, payload: 63, ramp rate: 4, target level: 0
MQTT 08.01.2024 08:38:58
* string: Setting 0/56/10 to 3.000, previous=255.000
MQTT Send Receive 08.01.2024 08:38:58
* string: Alias: 0/56/10, payload: 3, ramp rate: 4, target level: 0
MQTT final 08.01.2024 08:38:58
* string: Sending final level for 0/56/10 of 0
MQTT Send Receive 08.01.2024 08:38:58
* string: Alias: 0/56/10, payload: 0, ramp rate: 4, target level: 0
MQTT Send Receive 08.01.2024 08:38:58
* string: Clear ramp for 0/56/10
MQTT Send Receive 08.01.2024 08:38:58
* string: Publishing state and level cbus/read/254/56/10 to OFF/0
MQTT 08.01.2024 08:38:58
* string: Setting 0/56/10 to 0.000, previous=255.000
MQTT Send Receive 08.01.2024 08:38:58
* string: Alias: 0/56/10, payload: 0, ramp rate: 4, target level: 0
MQTT Send Receive 08.01.2024 08:38:58
* string: Set ramp for 0/56/10 and suppress zero send
MQTT Send Receive 08.01.2024 08:39:07
* string: Publishing state and level cbus/read/254/56/10 to OFF/0
MQTT Send Receive 08.01.2024 08:39:07
* string: Removing orphaned ramp for 0/56/10
MQTT 08.01.2024 08:39:13
* string: Setting 0/56/10 to 49.000, previous=0.000
MQTT Send Receive 08.01.2024 08:39:13
* string: Alias: 0/56/10, payload: 49, ramp rate: 4, target level: 255
MQTT Send Receive 08.01.2024 08:39:13
* string: Set ramp for 0/56/10
MQTT 08.01.2024 08:39:14
* string: Setting 0/56/10 to 109.000, previous=0.000
MQTT Send Receive 08.01.2024 08:39:14
* string: Alias: 0/56/10, payload: 109, ramp rate: 4, target level: 255
MQTT 08.01.2024 08:39:15
* string: Setting 0/56/10 to 169.000, previous=0.000
MQTT Send Receive 08.01.2024 08:39:15
* string: Alias: 0/56/10, payload: 169, ramp rate: 4, target level: 255
MQTT 08.01.2024 08:39:16
* string: Setting 0/56/10 to 229.000, previous=0.000
MQTT Send Receive 08.01.2024 08:39:16
* string: Alias: 0/56/10, payload: 229, ramp rate: 4, target level: 255
MQTT final 08.01.2024 08:39:17
* string: Sending final level for 0/56/10 of 255
MQTT Send Receive 08.01.2024 08:39:17
* string: Alias: 0/56/10, payload: 255, ramp rate: 4, target level: 255
MQTT Send Receive 08.01.2024 08:39:17
* string: Clear ramp for 0/56/10
MQTT Send Receive 08.01.2024 08:39:17
* string: Publishing state and level cbus/read/254/56/10 to ON/255
MQTT 08.01.2024 08:39:17
* string: Setting 0/56/10 to 255.000, previous=0.000
MQTT Send Receive 08.01.2024 08:39:17
* string: Alias: 0/56/10, payload: 255, ramp rate: 4, target level: 255
MQTT Send Receive 08.01.2024 08:39:17
* string: Set ramp for 0/56/10
MQTT Send Receive 08.01.2024 08:39:17
* string: Clear ramp for 0/56/10
MQTT Send Receive 08.01.2024 08:39:17
* string: Publishing state and level cbus/read/254/56/10 to ON/255
MQTT 08.01.2024 08:39:46
* string: Setting 0/56/10 to 231.000, previous=255.000
MQTT Send Receive 08.01.2024 08:39:46
* string: Alias: 0/56/10, payload: 231, ramp rate: 4, target level: 0
MQTT Send Receive 08.01.2024 08:39:46
* string: Set ramp for 0/56/10
MQTT 08.01.2024 08:39:47
* string: Setting 0/56/10 to 171.000, previous=255.000
MQTT Send Receive 08.01.2024 08:39:47
* string: Alias: 0/56/10, payload: 171, ramp rate: 4, target level: 0
MQTT 08.01.2024 08:39:48
* string: Setting 0/56/10 to 111.000, previous=255.000
MQTT Send Receive 08.01.2024 08:39:48
* string: Alias: 0/56/10, payload: 111, ramp rate: 4, target level: 0
MQTT 08.01.2024 08:39:49
* string: Setting 0/56/10 to 51.000, previous=255.000
MQTT Send Receive 08.01.2024 08:39:49
* string: Alias: 0/56/10, payload: 51, ramp rate: 4, target level: 0
MQTT final 08.01.2024 08:39:50
* string: Sending final level for 0/56/10 of 0
MQTT Send Receive 08.01.2024 08:39:50
* string: Alias: 0/56/10, payload: 0, ramp rate: 4, target level: 0
MQTT Send Receive 08.01.2024 08:39:50
* string: Clear ramp for 0/56/10
MQTT Send Receive 08.01.2024 08:39:50
* string: Publishing state and level cbus/read/254/56/10 to OFF/0
MQTT 08.01.2024 08:39:50
* string: Not setting 0/56/10 to 0.000, previous value is 0.000
MQTT 08.01.2024 08:40:08
* string: Setting 0/56/10 to 61.000, previous=0.000
MQTT Send Receive 08.01.2024 08:40:08
* string: Alias: 0/56/10, payload: 61, ramp rate: 4, target level: 255
MQTT Send Receive 08.01.2024 08:40:08
* string: Set ramp for 0/56/10
MQTT 08.01.2024 08:40:09
* string: Setting 0/56/10 to 121.000, previous=0.000
MQTT Send Receive 08.01.2024 08:40:09
* string: Alias: 0/56/10, payload: 121, ramp rate: 4, target level: 255
MQTT 08.01.2024 08:40:10
* string: Setting 0/56/10 to 181.000, previous=0.000
MQTT Send Receive 08.01.2024 08:40:10
* string: Alias: 0/56/10, payload: 181, ramp rate: 4, target level: 255
MQTT 08.01.2024 08:40:11
* string: Setting 0/56/10 to 241.000, previous=0.000
MQTT Send Receive 08.01.2024 08:40:11
* string: Alias: 0/56/10, payload: 241, ramp rate: 4, target level: 255
MQTT final 08.01.2024 08:40:12
* string: Sending final level for 0/56/10 of 255
MQTT Send Receive 08.01.2024 08:40:12
* string: Alias: 0/56/10, payload: 255, ramp rate: 4, target level: 255
MQTT Send Receive 08.01.2024 08:40:12
* string: Clear ramp for 0/56/10
MQTT Send Receive 08.01.2024 08:40:12
* string: Publishing state and level cbus/read/254/56/10 to ON/255
MQTT 08.01.2024 08:40:12
* string: Setting 0/56/10 to 255.000, previous=0.000
MQTT Send Receive 08.01.2024 08:40:12
* string: Alias: 0/56/10, payload: 255, ramp rate: 4, target level: 255
MQTT Send Receive 08.01.2024 08:40:12
* string: Set ramp for 0/56/10
MQTT Send Receive 08.01.2024 08:40:12
* string: Clear ramp for 0/56/10
MQTT Send Receive 08.01.2024 08:40:12
* string: Publishing state and level cbus/read/254/56/10 to ON/255
``` 
![mqtt final](https://github.com/autoSteve/acMqtt/assets/49742396/515a0baf-f41d-42ca-bf41-7cdc2a0b72a3)
![mqtt send receive](https://github.com/autoSteve/acMqtt/assets/49742396/075b3637-9d68-4f13-ac10-abe4daf97f9b)
![mqtt](https://github.com/autoSteve/acMqtt/assets/49742396/06480de9-8592-41d7-a9e5-74752cccc7d8)

**Comment by autoSteve** [comment]
Brilliant feedback. Thanks. It's working, but it can be better. My cunning plan for today is to see if I can eliminate event script 'MQTT' altogether for 1.15.0, in favour of just 'MQTT final'.

My thoughts regarding NOT SETTING is that possibly both MQTT and MQTT final are firing occasionally at the end of a ramp. This _should_ not bust anything. This is probably timing related, with me checking CBus ramp rate, which may reset to zero at some point after the ramp and would cause this.

In modern times, the whole idea of ramp tracking is to get rid of progressive sending of level during a ramp to HomeAssistant, as that makes it go crazy re. what #18 fixed. Historically, it was to suppress sending a zero level at the start of every ramp (ramp to zero would see 'MQTT' send something like 0, 190, 120, 60, 10, 0 to send receive, and this would make status in HA look really odd for ramps). 'MQTT final' will fire only at the end of a ramp, which is perfect now that AC feature bug is fixed.

I think I'll just need to upgrade MQTT final to check 'pre' storage items, and bypass a chunk of code in MQTT send receive, replacing it with something far simpler. I may be able to eliminate 'pre' storage altogether.

Re-opening #21

**Comment by autoSteve** [comment]
I've pushed a commit for 1.15.0+ optimisation, @sgraystar. I forgot to reference #21 in the commit comment, so letting you know.

This bypasses ramp tracking for 1.15.0+ as long as 'MQTT final' is installed. Event 'MQTT' must be removed or just disabled, so use either 'MQTT' or 'MQTT final', and not both. The script checks for this. 1.15.0+ can utilise 'MQTT', and it will switch to the legacy ramp tracking, warning on startup that an optimisation by using 'MQTT final' instead is preferred. For firmware less than 1.15.0 it refuses to start if 'MQTT final' is enabled. It also checks the 'Execute during ramping' setting of both scripts (it could actually set this, but only by using undocumented SQLlite manipulation methods, which I'd rather not do).

I've yet to update the readme.

**Comment by autoSteve** [comment]
Latest commit adds version checking for the event script in use. So if 'MQTT send receive' gets updated, but the event script ihas not been updated and is not a compatible version then 'MQTT send receive' will halt with an error.

Readme has also been updated.

**Comment by sgraystar** [comment]
MQTT final is working for me.

Minor: The script checking also needs to cater for scripts not being present. If MQTT final is being used and MQTT is deleted you get the error below.
I would guess it is probably similar if MQTT is being used and MQTT final is deleted.

Script version: https://github.com/autoSteve/acMqtt/commit/38d858837bc3f8c48dec3e7420c507aa749fbf33
Device: 5500AC2
Version: 1.15.0, hw v1.1

```
MQTT Send Receive 09.01.2024 07:52:39
* string: Error firmware > 1.15.0: Event script 'MQTT' is not set to execute during ramping. Not starting.
```

**Comment by autoSteve** [comment]
Thanks @sgraystar. It was just MQTT that had to be present. Fixed.
