### ISSUE TITLE
Temperature Sensors no longer being discovered in HA

### ISSUE THREAD

**Issue by arrikhan** [autoSteve/acMqtt#28]
After recent upgrades (am unsure how to reference what version of send receive script, as this has been removed along with the changelog), my temperatures sensors no longer get discovered/created in HA. I have deleted MQTT in HA and re added to rediscover and there seems to be some odd behaviour.

Events are being published to MQTT. 

MQTT published events
`cbus/read/0/228/34_1/level`

CBUS object keywords
`All, MQTT, sensor, unit= °C, dec=1, `

**Comment by autoSteve** [comment]
This is an interesting one, @arrikhan. A 'preferred name' pn= is not present in these measurement app keywords, so the script had no way of getting the measurement app channel name, instead utilising the measurement group tag (if that existed in the tag map) for every channel in the group.

Commit [38ddcc3](https://github.com/autoSteve/acMqtt/commit/38ddcc36e370d825e05cdf5c6209e3bc0b5434df) features a channel name lookup from the internal SQLite database, because there is no GetCBus.. function to do this as at firmware 1.15.0.

Let me know how this modified code goes.

**Comment by arrikhan** [comment]
Note, I had a “pn=xxxx” prior to example submitted below and attempted a reboot or two without it to see if it changed anything.

I have two sensors, one had disappeared originally and the second stayed but was unknown and I couldn’t delete it, hence my defence to weird behaviour. 

I will try new code and advise …

**Comment by arrikhan** [comment]
```
* string: Error publishing current values: [string "Resident"]:1046: attempt to index a nil value
* string: Error calling CBus create/update/delete function: [string "Resident"]:1046: attempt to index a nil value
```

Above is response on loading new code. Log continuously throws out last line.

I’ve added a pn=xxxx to temp sensors in SHAC which hasn’t changed outcome.

**Comment by autoSteve** [comment]
There must not be a name for that measurement app sensor in the tag map. Latest should suppress that error.

**Comment by arrikhan** [comment]
Note, device/sensor still not showing up ion HA

**Comment by arrikhan** [comment]
New code loaded.. Only seeing below now. No appearance of temp devices in HA (restarted HA also)

`* string: Error calling CBus create/update/delete function: [string "Resident"]:1047: attempt to index a nil value `

**Comment by autoSteve** [comment]
That's weird.

Count you confirm that your line 1047 looks like this?

```
      if resp ~= nil then grps[alias].name = resp[1]['tag'] else grps[alias].name = alias end
```

**Comment by arrikhan** [comment]
> That's weird.
> 
> Could you confirm that your line 1047 looks like this?
> 
> ```
>       if resp ~= nil then grps[alias].name = resp[1]['tag'] else grps[alias].name = alias end
> ```

Confirmed

**Comment by autoSteve** [comment]
Hmmm. Could you please replace that line with...

```
      if resp ~= nil and resp[1]['tag'] ~= nil then grps[alias].name = resp[1]['tag'] else grps[alias].name = alias end
```

**Comment by arrikhan** [comment]
same issue..

**Comment by autoSteve** [comment]
I need more info. Could you please add the two log() lines before that one and send me the result.

```
      log(alias, resp)
      log(grps[alias])
      if resp ~= nil and resp[1]['tag'] ~= nil then grps[alias].name = resp[1]['tag'] else grps[alias].name = alias end
```

And a look at your tag map would be good as well, as this code is good as gold for me.
<img width="294" alt="image" src="https://github.com/autoSteve/acMqtt/assets/37229860/125a4f49-6ad9-469e-bc84-827850700315">

**Comment by arrikhan** [comment]
I have nothing in tag map (there is no collapsed menu).

Here is additional log info

`* table:
 ["net"]
  * number: 0
 ["channel"]
  * number: 1
 ["keywords"]
  * string: All,MQTT,dec=1,pn=CBUS Inside Temperature,sensor,unit= °C
 ["group"]
  * number: 34
 ["tags"]
  * table:
 ["app"]
  * number: 228`

**Comment by arrikhan** [comment]
<img width="397" alt="image" src="https://github.com/autoSteve/acMqtt/assets/13254846/294c5f78-365d-4283-9297-abdd85b296c4">

Here is my CBUS temp sensor config

There is no application defined in measurement and I have no groups defined in temperature broadcast. This wasn't originally needed to get these devices on the network and publishing temp.

**Comment by autoSteve** [comment]
If you have nothing in tag map then that'd do it! I assume that you've never done a Toolkit CGL import, or have never set up the measurement app channel names. Change 1047.

This will use the alias for the sensor name (if there is nothing in the tag map), or use pn= keyword for the name, which for your situation consider pn= mandatory.

```
      if resp ~= nil and resp[1] ~= nil and resp[1]['tag'] ~= nil then grps[alias].name = resp[1]['tag'] else grps[alias].name = alias end
```

**Comment by arrikhan** [comment]
MAGIC! Thanks .. !

<img width="408" alt="image" src="https://github.com/autoSteve/acMqtt/assets/13254846/21f1d825-862b-4eeb-8e46-776c109ae191">

**Comment by arrikhan** [comment]
> If you have nothing in tag map then that'd do it! I assume that you've never done a Toolkit CGL import, or have never set up the measurement app channel names. Change 1047.

Where do you setup Channel Names for Measurement App? CBUS Toolkit doesn't show it, and I don't use PICED anymore after ditching my Wiser.

**Comment by autoSteve** [comment]
How odd that you don't have anything in the tag map!

Creating a measurement app device and channel in an Automation Controller requires that a name be provided, and this is placed in the tag map.

<img width="544" alt="image" src="https://github.com/autoSteve/acMqtt/assets/37229860/47762143-ee98-4eed-a504-63ffb4877878">

<img width="225" alt="image" src="https://github.com/autoSteve/acMqtt/assets/37229860/19c56b70-fd97-4035-a55a-e291c5c00f7e">
