### ISSUE TITLE
Edge Case: Error occurs if C-Bus group exists, but never had a level set (.i.e is nil)

### ISSUE THREAD

**Issue by pbyrne-ms** [autoSteve/acMqtt#3]
The error comes from : 'MQTT send/receive'

Can happen after SHAC reboots, or if you create a new object from the SHAC and don't give it a value.
(once you set group to any value 0-255, the error does not occur anymore) 

SHAC Error Log:

`Library cbuslogic:0: unable to decode for 0/56/30
stack traceback:
 [C]: in function 'error'
 Library cbuslogic: in function '_GetCBusLightData'
 Library cbuslogic: in function 'GetCBusLevel'
 Resident script:759: in function 'outstandingPublish'`

 line 759 is :
 `else publish(tNetCBus(u.net), u.app, u.group, GetCBusLevel(u.net, u.app, u.group))`
 
 so it's probably the 'GetCBusLevel' function...

**Comment by pbyrne-ms** [comment]
hmm... not getting anywhere much with this... All I have got working so far is

`else publish(tNetCBus(u.net), u.app, u.group, grp.getvalue(u.net, u.app, u.group))`

reverting to the logic-machine basic syntax command "grp.getvalue", which at least returns a real nil object, and allows the script to execute....

Whatever magic Schneider put into the 'GetCBusLevel' function call does not actually seem to return nil, it just throws an error, halting the script... not sure how to programmatically check for this error/return code... I guess if this was possible you could check it and do If/else return 0, or something similar...

**Comment by autoSteve** [comment]
Good pick up. Just added a commit to try and solve for this. I ignore the error.

I will check whether the get user param also suffers the same fate. Might look at measurement app, too. Or maybe just switch to grp.getvalue.

**Comment by autoSteve** [comment]
GetCBusMeasurement also errors. GetUserParam does not, and returns an empty string value. Will fix measurement and add another commit.

**Comment by pbyrne-ms** [comment]
Cheers for that, there doesn't appear to be a better way to do this, other than check it via pcall, that I can find at least...
The way it now works for me anyhow - Cheers!
