### ISSUE TITLE
HA friendly_name problem

### ISSUE THREAD

**Issue by sgraystar** [autoSteve/acMqtt#45]
Gday Steve, this definitely in the low priority list.

I was tinkering in HA and found the following with friendly name.

Device: 5500AC2
Version: 1.15.0, hw v1.1
Script version: https://github.com/autoSteve/acMqtt/commit/dd6c72ba16f04ea1e20eea3baff8e64511a56ee2

--[[ SET AS APPROPRIATE TO SUIT ENVIRONMENT --]]
all false

Lighting GA, add keywords: MQTT, cover, noleveltranslate, sa=ZZZ, img=mdi:roller-shade, 
HA friendly_name has a space character appended to the tag name.
```
friendly_name: "ext blind 6 "
``` 

Lighting GA, add keywords: MQTT, cover, noleveltranslate, pn='ext blind 6', sa=ZZZ, img=mdi:roller-shade, 
HA friendly name includes the quotation marks.
```
friendly_name: "'ext blind 06'"
``` 

Lighting GA, add keywords: MQTT, cover, noleveltranslate, pn=extblind6, sa=ZZZ, img=mdi:roller-shade, 
HA friendly_name has a space character appended to the end.
```
friendly_name: "extblind6 "
```

**Comment by autoSteve** [comment]
From the doco...

_The ```friendly_name``` state attribute is generated by combining then entity name with the device name as follows:

The entity is not a member of a device: ```friendly_name = entity.name```
The entity is a member of a device and ```entity.name``` is not ```None```: ```friendly_name = f"{device.name} {entity.name}"```
The entity is a member of a device and ```entity.name``` is ```None```: ```friendly_name = f"{device.name}"```_

I am setting ```entity.name``` to '', and not ```None```. I changed that and nothing blew up, so I'll create a branched commit for you to test my thinking. Stand by.

**Comment by autoSteve** [comment]
Give [f579905](https://github.com/autoSteve/acMqtt/commit/f5799054272aff7a13be81a0fe45a1451123cb38) a go, or change line 787 to ```payload.name = nil```.

**Comment by autoSteve** [comment]
Something is weird with this change. "MQTT blah" is being appended to preferred names...

<img width="501" alt="image" src="https://github.com/autoSteve/acMqtt/assets/37229860/a1fc0487-53ab-4f6e-93ed-18bb80d4c580">

**Comment by sgraystar** [comment]
and I think it may be a HA bug, MQTT Explorer looks fine

**Comment by autoSteve** [comment]
Indeed.

What does ```friendly_name``` look like now? (I couldn't work out how to display that for MQTT discovery.)

**Comment by sgraystar** [comment]
Yeah, the line 787 did something else so I reverted.

I was looking at the dev.ids and dev.name parameters in MQTT explorer which look fine.
And HA Developer Tools, States, Select a cover entity so you can set state. This shows a space at the end of friendly_name, which I hit when expecting to get a digit from an automation with {{ state_attr(trigger.entity_id, 'friendly_name')[-1] }}

Unless this is changed somehow when publishing new values I guess this is a HA bug?

But the the below is still a bug:
Lighting GA, add keywords: MQTT, cover, noleveltranslate, pn='ext blind 6', sa=ZZZ, img=mdi:roller-shade,
MQTT explorer and HA friendly name includes the quotation marks in the string.

```
friendly_name: "'ext blind 06'"
```

**Comment by autoSteve** [comment]
> But the the below is still a bug: (the quotes)

Kind of. It's actually by design that any quotation marks are included. Example: ```Steve's bedside light``` or ```"Bleep" of a device```

I'm currently trawling through the HA source to see what is causing ```MQTT LightEntity```, etc. to be appended. This is not in the documentation.

**Comment by sgraystar** [comment]
OK, that makes sense

**Comment by autoSteve** [comment]
I have more than a theory.

Each MQTT thing has a 'default' name in the source code, and by setting payload.name to nil this is removing payload.name from the JSON. Contrast this with a discovery item from Zigbee2MQTT, where it features a specific ```"name": none```.

I am going to need to hack this, as LUA is to blame.

<img width="300" alt="image" src="https://github.com/autoSteve/acMqtt/assets/37229860/0ce3e23d-5e9a-4061-94db-4557028cc3ec">

**Comment by sgraystar** [comment]
leave as-is and cover on readme ...

**Comment by autoSteve** [comment]
Nah. It's annoying me.

**Comment by autoSteve** [comment]
This commit pleases me greatly, @sgraystar. Should do the trick.

**Comment by sgraystar** [comment]
all fixed
