### ISSUE TITLE
Resident script:294: attempt to index a nil value

### ISSUE THREAD

**Issue by OrigSorceror** [autoSteve/acMqtt#53]
using the current MQTT send receive script but getting this error in my SHAC5500 error logs

Resident script:294: attempt to index a nil value
stack traceback:
 Resident script:294: in function <Resident script:289>
 [C]: in function 'loop'

MQTT successfully connects to broker. but no devices are picked up in HAOS. 
5500SHAC Firmware Version 1.6.0
5500SHAC HW version 1.0

**Comment by autoSteve** [comment]
Change line 294 and restart.

Old:
```
      if parts[3]:contains('cbus_mqtt_') then
```

New:
```
      if parts[3] ~= nil and parts[3]:contains('cbus_mqtt_') then
```

What I think is going on here is that you likely have a HA discovery topic (something like homeassistant/sensor) that does not contain any sub-topics. This can be verified in MQTT Explorer, but it makes sense.

<img width="600" alt="image" src="https://github.com/user-attachments/assets/94f3e18e-e2ee-45de-8be8-9c9c4acf3ae3">

**Comment by OrigSorceror** [comment]
Ok that fixed the error, but still nothing being reported in HAOSNo new devices found and no nee entries in Mosquito. Sent from my iPhoneOn 14 Aug 2024, at 10:36 AM, Steve Saunders ***@***.***> wrote:﻿
Change line 294 and restart.
Old:
      if parts[3]:contains('cbus_mqtt_') then

New:
      if parts[3] ~= nil and parts[3]:contains('cbus_mqtt_') then

What I think is going on here is that you likely have a HA discovery topic (something like homeassistant/sensor) that does not contain any sub-topics. This can be verified in MQTT Explorer, but it makes sense.
image.png (view on web)

**Comment by autoSteve** [comment]
Oh come on, @OrigSorceror. You are going to need to provide a HEAP more information, otherwise I am just guessing and probably can't help. One line descriptions from an iPhone saying, "_it works but it don't work_" give me nothing.

That this error even occurred hints at something not being right with the HA discovery topics.

* What is in the SHAC log? If nothing of import then in the code change `local logging = false` to `true` and restart
* Is there anything in the SHAC error log?
* Examples of your keywords configured for SHAC objects
* Screen shots of what the `homeassistant/` topics look like in MQTT Explorer

**Comment by OrigSorceror** [comment]
ok made code change to turn on logging. 
nothing in error logs. 
Log show
![image](https://github.com/user-attachments/assets/f5afc688-1562-4b3c-a55c-466f6e2e6248)
.. 

MQTT Explorer shows
![image](https://github.com/user-attachments/assets/02c11278-6294-451b-ad99-92c5677ffb69)

**Comment by OrigSorceror** [comment]
I may not have Mosquitto set up correctly in HAOS.  AS there is now HomeAssistant section in the explorer like yours.
I also operate the CBUS network on a different Physical network with only a router and Rpi bridging the 2 networks.. currently whilst building this HAOS implementation, i have allowed all traffic between all IPs on both Networks so i doubt it is a network issue.. 

I halso have CBUS up and running via Homebridge tied in to Apple at the moment whilst i play with the HAOS (have not enable apple integration on HA as yet)

**Comment by autoSteve** [comment]
Looks like HomeAssistant is not configured for MQTT.

There are no discovery topics at all.

Did you miss this in `configuration.yaml`?

```
mqtt:
```

**Comment by OrigSorceror** [comment]
nope that is in there
just made some changes to the config.yaml and restarting HAOS to apply..

**Comment by autoSteve** [comment]
What keywords are added to the SHAC objects? Example:

```
MQTT, light, sa=Family Room, pn=Family Room Lights, 
```

**Comment by OrigSorceror** [comment]
Bingo!!!  missing keywords.  LOL must have glossed over that section of the setup instructions  Sorry little dyslexic :(

**Comment by OrigSorceror** [comment]
just added keywords to 1 of the lights and it is discovered. :)  All good to close issue

**Comment by autoSteve** [comment]
Cheers.
