### ISSUE TITLE
Nil event log noise

### ISSUE THREAD

**Issue by crispyoz** [autoSteve/acMqtt#57]
I just started using this script since I just started using Home Assistant to replace my now failed CBUS screen.   The 5500SHAC logs contain an error on startup, so I modified this line:

Was:

> value = event.getvalue()

Changed to:

**if event ~= nil then value = event.getvalue() else value = nil end**

Perhaps a bit anal but I hate noisey logs

**Comment by autoSteve** [comment]
Welcome aboard, @crispyoz!

I have no idea how many are using these scripts, unlike over at the Solcast solar forecast integration, which is another pet project. (https://github.com/BJReplay/ha-solcast-solar).

My curiosity is piqued...

The script `MQTT send receive` does not feature a line `value = event.getvalue()` anywhere, which makes sense given it is a resident. The event-based script of old **_did_** carry that line. I retired that separate script and instead now monitor the local event bus with a callback using just one resident script: `MQTT send receive`.

Upgrade instead to avoid eye twitch?

I am curious as to what was causing your error. An event-based script should only fire when an event happens, in which case the `event` table will exist. That test should not be necessary.

```
--[[
  ** NOTE: This script at one stage relied on an event-based script 'MQTT final' or 'MQTT'. This event script is no longer needed, and can be deleted.
  ** If named correctly, this resident script will disable the event-based script on startup, but even if it is enabled it will not cause any issue.
--]]
```

**Comment by autoSteve** [comment]
If a script that is designed as an event-based script were installed as a resident script then I have no idea what the outcome would be, apart from a certainty of errors in the log. The table `event` would not exist on execute, so 💣...

**Comment by autoSteve** [comment]
The change to localbus and retire event-based script was in early April 2024, BTW.

**Comment by autoSteve** [comment]
All good!

With Home Assistant there is a rigid publish-a-release thing going on, even for HACS custom components like Solcast Solar. This is a good thing.

With the Automation Controller it is pretty much the wild west for acquiring GitHub scripting, so I feel your pain. 😂

You've found my shit now, so everything will be all right...

Technically I have saved you many hundreds of hours. Integrating C-Bus in Lua for MQTT started as about a hundred lines of code and swelled from there. I run this, so it must be right. It must be optimised for efficiency. Many others run this, so it must be right for them also.

And it must be right for you, too. So welcome again.

Any dramas, holler!

I'm a Python guy these days, but do C++/Lua (and more). Given you're new to Home Assistant, check out HACS. There be many wonderous things Home Assistant that are not out-of-the-box Home Assistant!
